# Generated by Django 5.2.7 on 2025-12-04 10:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="test_stream",
            field=wagtail.fields.StreamField(
                [
                    ("simple_reorder", 3),
                    ("person", 10),
                    ("employee", 15),
                    ("article", 22),
                    ("testimonial", 27),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageBlock", [], {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("photo", 0),
                                ("surname", 1),
                                ("first_name", 1),
                                ("biography", 2),
                            ]
                        ],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Whether this person is available",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show contact info on public profile",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Email address (required)", "required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "Light"),
                                ("dark", "Dark"),
                                ("primary", "Primary Color"),
                                ("secondary", "Secondary Color"),
                            ],
                            "help_text": "Select the color theme",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                            ],
                            "help_text": "Select the font size",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("photo", 0),
                                ("surname", 1),
                                ("first_name", 1),
                                ("biography", 2),
                                ("job_title", 4),
                                ("department", 4),
                                ("available", 5),
                                ("display_contact", 6),
                                ("email", 7),
                                ("theme", 8),
                                ("font_size", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Job role or position"},
                    ),
                    12: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Employee ID number", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Is this employee currently active",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("photo", 0),
                                ("surname", 1),
                                ("first_name", 1),
                                ("role", 11),
                                ("biography", 2),
                                ("job_title", 4),
                                ("department", 4),
                                ("start_date", 12),
                                ("employee_id", 13),
                                ("active_status", 14),
                                ("available", 5),
                                ("display_contact", 6),
                                ("email", 7),
                                ("theme", 8),
                                ("font_size", 9),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Brief introduction", "required": False},
                    ),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("intro", 16),
                                ("image", 17),
                                ("body", 2),
                                ("image_caption", 4),
                                ("alignment", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Feature this article on the homepage",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("news", "News"),
                                ("blog", "Blog"),
                                ("announcement", "Announcement"),
                            ],
                            "help_text": "Article category",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 1),
                                ("subheading", 4),
                                ("author", 4),
                                ("content", 19),
                                ("publish_date", 12),
                                ("featured", 20),
                                ("category", 21),
                                ("theme", 8),
                                ("font_size", 9),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.TextBlock", (), {}),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("5", "5 stars"),
                                ("4", "4 stars"),
                                ("3", "3 stars"),
                            ],
                            "help_text": "Testimonial rating",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Display the rating",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("card", "Card"),
                                ("inline", "Inline"),
                                ("banner", "Banner"),
                            ],
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 23),
                                ("author_name", 1),
                                ("author_title", 4),
                                ("author_photo", 0),
                                ("company", 4),
                                ("company_logo", 17),
                                ("rating", 24),
                                ("show_rating", 25),
                                ("layout_style", 26),
                                ("theme", 8),
                                ("font_size", 9),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
